apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod
  labels:
    app: mysql-pod
spec:
  containers:
    - name: mysql-pod
      image: mysql:5.7
      ports:
        - containerPort: 3306
      env:
      - name: MYSQL_ROOT_PASSWORD
        value: "!Abc123"
      - name: MYSQL_ALLOW_EMPTY_PASSWORD
        value: "no"
      - name: MYSQL_RANDOM_ROOT_PASSWORD
        value: "no"